import './globals.css'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import Link from 'next/link'
import LogoutButton from './logout-button'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user },
  } = await supabase.auth.getUser()

  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-slate-950 flex flex-col items-center">
          <div className="flex-1 flex flex-col max-w-3xl mt-24">
            <h1 className="text-2xl mb-2 flex justify-between">
              <span className="sr-only">Blog Admin Portal</span>
            </h1>
            <div className="flex border-b py-3 text-sm text-neutral-100">
              <span className="ml-auto">
                {user ? (
                  <span className="flex gap-4">
                    Hey, {user.email}! <span className="border-r"></span>{' '}
                    <LogoutButton />
                  </span>
                ) : (
                  <Link href="/login" className="text-neutral-100 hover:underline">
                    Login
                  </Link>
                )}
              </span>
            </div>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
