create table "public"."paragraphs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "body" character varying,
    "ui_order" smallint,
    "post_id" bigint
);


alter table "public"."paragraphs" enable row level security;

create table "public"."posts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "title" character varying
);


alter table "public"."posts" enable row level security;

CREATE UNIQUE INDEX paragraphs_pkey ON public.paragraphs USING btree (id);

CREATE UNIQUE INDEX posts_pkey ON public.posts USING btree (id);

alter table "public"."paragraphs" add constraint "paragraphs_pkey" PRIMARY KEY using index "paragraphs_pkey";

alter table "public"."posts" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";

alter table "public"."paragraphs" add constraint "paragraphs_post_id_fkey" FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE not valid;

alter table "public"."paragraphs" validate constraint "paragraphs_post_id_fkey";


